name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update && sudo apt-get install -y\
          build-essential libbsd-dev libelf-dev libjson-c-dev\
          libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
          pkg-config
    - name: Install libbpf
      run: |
        wget -q -O - https://github.com/libbpf/libbpf/archive/refs/tags/v0.3.tar.gz \
        | tar -xzC ${GITHUB_WORKSPACE} \
        && make -j -C ${GITHUB_WORKSPACE}/libbpf-0.3/src install
    - name: make
      run: make
