name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update && sudo apt-get install -y\
          build-essential libbpf-dev libbsd-dev libelf-dev libjson-c-dev\
           libnl-3-dev libnl-cli-3-dev libnuma-dev libpcap-dev meson\
           pkg-config
    - name: make
      run: make
